default:
  @just --list

bios:
  systemctl reboot --firmware-setup

changelogs:
  rpm-ostree db diff --changelogs

distrobox-appbox:
  echo 'Creating Appbox distrobox ...'
  distrobox create --image fedoraproject.org/fedora-toolbox:37 -n appbox -Y

distrobox-fedbox:
  echo 'Creating Fedbox distrobox ...'
  distrobox create --image fedoraproject.org/fedora-toolbox:37 -n fedbox -Y

setup-pwa:
  echo 'Giving browser permission to create PWAs (Progressive Web Apps)'
  # Add for your favorite chromium-based browser
  flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.github.Eloston.UngoogledChromium

setup-gaming:
  echo 'Setting up gaming experience ... lock and load.'
  flatpak install -y --user \\
  org.freedesktop.Platform.VulkanLayer.MangoHud//22.08 \\
  org.freedesktop.Platform.VulkanLayer.vkBasalt//22.08 \\
  net.lutris.Lutris \\
  com.usebottles.bottles \\
  com.valvesoftware.Steam \\
  com.valvesoftware.Steam.Utility.gamescope \\
  net.davidotek.pupgui2
  flatpak override com.usebottles.bottles --user --filesystem=xdg-data/applications 
  flatpak override --user --env=MANGOHUD=1 com.valvesoftware.Steam 
  flatpak override --user --env=MANGOHUD=1 com.heroicgameslauncher.hgl 
 
update:
  rpm-ostree update
  flatpak update -y
  distrobox upgrade -a
